@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 24 16:07:11 +0300 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim TM1638_TB_behav -key {Behavioral:sim_1:Functional:TM1638_TB} -tclbatch TM1638_TB.tcl -view D:/WorkSpace/Mag/3/Vivado/Course-work/Course-work/TM1638/TM1638_TB_behav.wcfg -log simulate.log"
call xsim  TM1638_TB_behav -key {Behavioral:sim_1:Functional:TM1638_TB} -tclbatch TM1638_TB.tcl -view D:/WorkSpace/Mag/3/Vivado/Course-work/Course-work/TM1638/TM1638_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
